(function(root){
  'use strict';
  const fields=[['identity','Identity','Adult name, role, and setting.'],['motivation','Motivation','What do they actively want?'],['value','Non-negotiable value','What will they refuse to trade for their goal?'],['normal','Normal behavior','What observable things do they do when comfortable?'],['stress','Behavior under pressure','How do choices and speech change when threatened?'],['trust','Trust progression','What small change shows earned trust?'],['voice','Voice examples','Two short original lines; one per line.'],['scene','Opening scene','A concrete problem and a choice for the user.']];
  const example={identity:'Iris Vale, 32, a museum conservator working after closing time.',motivation:'Recover the provenance of a donated painting before the exhibition opens.',value:'Never present an attractive guess as an established fact.',normal:'Asks one precise question at a time and offers practical help before discussing herself.',stress:'Becomes more formal and checks the evidence aloud; refuses to sign an unsupported attribution.',trust:'Invites the user to inspect her unfinished notes and admits which part of the problem worries her.',voice:'That is a lovely theory. Unfortunately, the varnish disagrees.\nI can promise a careful answer. A quick one would cost extra in mistakes.',scene:'A painting arrives with two incompatible donor letters. Iris sets them beside the frame and asks which discrepancy the user would like to investigate first.'};
  const clean=d=>Object.fromEntries(fields.map(([k])=>[k,typeof d?.[k]==='string'?d[k].trim():'']));
  function review(input){const d=clean(input),notes=[];for(const[k,label]of fields)if(!d[k])notes.push('Add '+label.toLowerCase()+'.');if(d.normal&&d.normal.toLowerCase()===d.stress.toLowerCase())notes.push('Normal and pressure behavior are identical. Explain what changes, or why it stays the same.');if(d.voice&&d.voice.split(/\n/).filter(s=>s.trim()).length<2)notes.push('Add a second voice example on a new line.');if(!notes.length)notes.push('Basic completeness checks passed. Review the five scenarios manually; this is not a quality score.');return notes;}
  function markdown(input){const d=clean(input);return '# Character brief\n\n'+fields.map(([k,label])=>'## '+label+'\n'+(d[k]||'[Not specified]')).join('\n\n')+'\n\n## Interaction boundary\nWrite only this character\'s actions and dialogue. Do not decide the user\'s thoughts, feelings, consent, or next action. Keep all participants adults.\n';}
  const api={fields,example,clean,review,markdown};root.PersonalityKit=api;if(typeof module!=='undefined')module.exports=api;
})(typeof globalThis!=='undefined'?globalThis:this);
