(function(root){
  'use strict';
  const fields=[['location','Location','Where are the characters now?'],['time','Time','Use an explicit time or an established relative time.'],['items','Item locations and holders','One item per line. An item on a desk does not imply a holder.'],['goal','Unresolved goal','Do not mark a goal complete without an established event.'],['constraints','Current constraints','Locked doors, unavailable resources, and other established limits.'],['unknowns','Unknown facts','What must the model ask about or leave unresolved?'],['freedom','Allowed creative detail','What can be invented without changing established facts?']];
  const clean=input=>Object.fromEntries(fields.map(([key])=>[key,typeof input?.[key]==='string'?input[key].trim():'']));
  const before=clean({location:'Museum archive',time:'5 pm',items:'Brass key: on the archive desk; no holder established.',goal:'Unknown',constraints:'Unknown',unknowns:'Who will take the key; the next task.',freedom:'Minor gestures and tone; do not invent item transfers or decide the visitor’s actions.'});
  const after=clean({location:'Museum courtyard',time:'5:20 pm',items:'Brass key: carried by the adult visitor.\nLedger: carried by Iris.',goal:'Find which exhibition case is missing its inventory label.',constraints:'The archive is locked.',unknowns:'Which case has the missing label; whether the key unlocks the archive.',freedom:'Minor gestures and tone. Ask before adding new physical layout, access, or item transfers.'});
  function changes(previous,current){const a=clean(previous),b=clean(current);return fields.filter(([key])=>a[key]!==b[key]).map(([key,label])=>({field:key,label,before:a[key],after:b[key]}));}
  function markdown(input){const state=clean(input);return '# Current scene state\n\n'+fields.map(([key,label])=>'## '+label+'\n'+(state[key]||'[Unknown — not supplied]')).join('\n\n')+'\n';}
  function prompt(input){return 'Use the following human-reviewed scene state as the latest update. It supersedes conflicting earlier scene facts. Empty or unknown fields are not permission to guess. Do not decide the user’s actions or dialogue. Ask if the next action depends on a missing fact.\n\n'+markdown(input)+'\nBefore continuing, check item locations and holders, access constraints, and unresolved goals. Creative detail must stay within the allowed scope.\n';}
  function review(input){const d=clean(input),notes=[];for(const[key,label]of fields)if(!d[key])notes.push(label+': not supplied; export will mark it unknown.');notes.push('Manual check: compare every claim with the conversation. This tool cannot verify truth or detect contradictions in prose.');return notes;}
  function bundle(previous,current){return {format:'crushonai-scene-state',version:1,previous:clean(previous),current:clean(current)};}
  function parse(text){const data=JSON.parse(text);if(!data||data.format!=='crushonai-scene-state'||data.version!==1)throw new Error('Expected a scene-state export with format version 1.');for(const name of ['previous','current']){if(!data[name]||typeof data[name]!=='object'||Array.isArray(data[name]))throw new Error('Missing '+name+' state.');for(const[key]of fields)if(typeof data[name][key]!=='string'||data[name][key].length>6000)throw new Error('Each state field must be text, at most 6,000 characters.');}return bundle(data.previous,data.current);}
  const api={fields,clean,before,after,changes,markdown,prompt,review,bundle,parse};root.SceneStateKit=api;if(typeof module!=='undefined')module.exports=api;
})(typeof globalThis!=='undefined'?globalThis:this);
